# Use postgres/example user/password credentials
version: '3.8'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - # host:container
      - "5432:5432"
    environment:
      POSTGRES_USER: #set db username
      POSTGRES_PASSWORD: #set db password
      POSTGRES_DB: # default db name
    networks:
      apipostgres:

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: # pgadmin user email
      PGADMIN_DEFAULT_PASSWORD: # pgadmin password
    ports:
      - # host:container
    networks:
      apipostgres:

  # If you want to run api in contrainer as well
  #  app:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    ports:
  #      - "5031:8080"
  #    links:
  #      - db
  #    depends_on:
  #      - db
  #    networks:
  #      apipostgres:

volumes:
  dbdata:

networks:
  apipostgres: